- name: Change docker home folder, make default local docker network IP size smaller
  shell: >-
       jq '. += { "data-root": "/docker", "default-address-pools" : [{"base" : "172.17.0.0/12","size" : 20},{"base" : "192.168.0.0/16","size" : 24}] }' /etc/docker/daemon.json > tmp.json && mv tmp.json /etc/docker/daemon.json

- name: Restart docker
  shell: systemctl restart docker
