
# NOTE: Docker compose V1 was deprecated June2023. This should be removed in the future.
- name: download the 1.26.2 release and save the executable file at /usr/local/bin/docker-compose
  shell: sudo curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: Set the correct permissions so that the docker-compose command is executable
  shell: chmod +x /usr/local/bin/docker-compose
